/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0] Y;

  //Multipliers:

  wire signed [31:0]
    w1,
    w4,
    w5,
    w256,
    w257,
    w10240,
    w10497,
    w83976,
    w83977;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w256 = w1 << 8;
  assign w257 = w1 + w256;
  assign w10240 = w5 << 11;
  assign w10497 = w257 + w10240;
  assign w83976 = w10497 << 3;
  assign w83977 = w1 + w83976;

  assign Y = w83977;

endmodule //multiplier_block

