/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0] Y;

  //Multipliers:

  wire signed [31:0]
    w1,
    w8,
    w7,
    w512,
    w513,
    w28672,
    w29185,
    w933920;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w7 = w8 - w1;
  assign w512 = w1 << 9;
  assign w513 = w1 + w512;
  assign w28672 = w7 << 12;
  assign w29185 = w513 + w28672;
  assign w933920 = w29185 << 5;

  assign Y = w933920;

endmodule //multiplier_block

