/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0] Y;

  //Multipliers:

  wire signed [31:0]
    w1,
    w64,
    w65,
    w2,
    w67,
    w266240,
    w266307,
    w532614;

  assign w1 = X;
  assign w64 = w1 << 6;
  assign w65 = w1 + w64;
  assign w2 = w1 << 1;
  assign w67 = w65 + w2;
  assign w266240 = w65 << 12;
  assign w266307 = w67 + w266240;
  assign w532614 = w266307 << 1;

  assign Y = w532614;

endmodule //multiplier_block

