/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0] Y;

  //Multipliers:

  wire signed [31:0]
    w1,
    w4,
    w5,
    w80,
    w85,
    w1280,
    w1365,
    w349440,
    w349525,
    w699050;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w80 = w5 << 4;
  assign w85 = w5 + w80;
  assign w1280 = w5 << 8;
  assign w1365 = w85 + w1280;
  assign w349440 = w1365 << 8;
  assign w349525 = w85 + w349440;
  assign w699050 = w349525 << 1;

  assign Y = w699050;

endmodule //multiplier_block

