/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0] Y;

  //Multipliers:

  wire signed [31:0]
    w1,
    w32,
    w33,
    w256,
    w223,
    w135168,
    w134945,
    w4,
    w5,
    w269890,
    w269895,
    w539790,
    w539791;

  assign w1 = X;
  assign w32 = w1 << 5;
  assign w33 = w1 + w32;
  assign w256 = w1 << 8;
  assign w223 = w256 - w33;
  assign w135168 = w33 << 12;
  assign w134945 = w135168 - w223;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w269890 = w134945 << 1;
  assign w269895 = w5 + w269890;
  assign w539790 = w269895 << 1;
  assign w539791 = w1 + w539790;

  assign Y = w539791;

endmodule //multiplier_block

