/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0] Y;

  //Multipliers:

  wire signed [31:0]
    w1,
    w2,
    w3,
    w6,
    w7,
    w192,
    w185,
    w24,
    w23,
    w94720,
    w94743,
    w378972,
    w378971,
    w757942;

  assign w1 = X;
  assign w2 = w1 << 1;
  assign w3 = w1 + w2;
  assign w6 = w3 << 1;
  assign w7 = w1 + w6;
  assign w192 = w3 << 6;
  assign w185 = w192 - w7;
  assign w24 = w3 << 3;
  assign w23 = w24 - w1;
  assign w94720 = w185 << 9;
  assign w94743 = w23 + w94720;
  assign w378972 = w94743 << 2;
  assign w378971 = w378972 - w1;
  assign w757942 = w378971 << 1;

  assign Y = w757942;

endmodule //multiplier_block

