/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0] Y;

  //Multipliers:

  wire signed [31:0]
    w1,
    w8,
    w9,
    w72,
    w71,
    w9216,
    w9145,
    w2,
    w3,
    w585280,
    w585283;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w9 = w1 + w8;
  assign w72 = w9 << 3;
  assign w71 = w72 - w1;
  assign w9216 = w9 << 10;
  assign w9145 = w9216 - w71;
  assign w2 = w1 << 1;
  assign w3 = w1 + w2;
  assign w585280 = w9145 << 6;
  assign w585283 = w3 + w585280;

  assign Y = w585283;

endmodule //multiplier_block

