/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0] Y;

  //Multipliers:

  wire signed [31:0]
    w1,
    w8,
    w7,
    w896,
    w895,
    w28672,
    w29567,
    w473072,
    w473071,
    w946142;

  assign w1 = X;
  assign w8 = w1 << 3;
  assign w7 = w8 - w1;
  assign w896 = w7 << 7;
  assign w895 = w896 - w1;
  assign w28672 = w7 << 12;
  assign w29567 = w895 + w28672;
  assign w473072 = w29567 << 4;
  assign w473071 = w473072 - w1;
  assign w946142 = w473071 << 1;

  assign Y = w946142;

endmodule //multiplier_block

