/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0] Y;

  //Multipliers:

  wire signed [31:0]
    w1,
    w2,
    w3,
    w32,
    w33,
    w1536,
    w1503,
    w384768,
    w384765,
    w769530;

  assign w1 = X;
  assign w2 = w1 << 1;
  assign w3 = w1 + w2;
  assign w32 = w1 << 5;
  assign w33 = w1 + w32;
  assign w1536 = w3 << 9;
  assign w1503 = w1536 - w33;
  assign w384768 = w1503 << 8;
  assign w384765 = w384768 - w3;
  assign w769530 = w384765 << 1;

  assign Y = w769530;

endmodule //multiplier_block

