/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0] Y;

  //Multipliers:

  wire signed [31:0]
    w1,
    w16,
    w15,
    w14,
    w7,
    w480,
    w487,
    w60,
    w67,
    w997376,
    w997309;

  assign w1 = X;
  assign w16 = w1 << 4;
  assign w15 = w16 - w1;
  assign w14 = w15 - w1;
  assign w7 = w14 >> 1;
  assign w480 = w15 << 5;
  assign w487 = w7 + w480;
  assign w60 = w15 << 2;
  assign w67 = w7 + w60;
  assign w997376 = w487 << 11;
  assign w997309 = w997376 - w67;

  assign Y = w997309;

endmodule //multiplier_block

