/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [31:0] X;
  output signed  [31:0] Y;

  //Multipliers:

  wire signed [31:0]
    w1,
    w128,
    w127,
    w126,
    w63,
    w130048,
    w130111,
    w1040888,
    w1040887;

  assign w1 = X;
  assign w128 = w1 << 7;
  assign w127 = w128 - w1;
  assign w126 = w127 - w1;
  assign w63 = w126 >> 1;
  assign w130048 = w127 << 10;
  assign w130111 = w63 + w130048;
  assign w1040888 = w130111 << 3;
  assign w1040887 = w1040888 - w1;

  assign Y = w1040887;

endmodule //multiplier_block

